version: '3.9'
services:
  db:
    image: "postgres:alpine3.19"
    restart: "always"
    environment:
      POSTGRES_DB: actix_demo
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - "5432:5432"